### PR TITLE
added config option to skip the local configuration

### PR DESCRIPTION
**Pull request by treaz**
This fixes issue #7

### CODE REVIEW

**Comment by treaz** [comment]
this is not correct... I'll redo it

**Comment by mehcode** [comment]
@treaz Why do you need a `skipLocal` option? https://github.com/lorenwest/node-config (which this is based from) doesn't have that.

**Comment by treaz** [comment]
@mehcode nevermind. It was a bad idea anyway :)

**Comment by mehcode** [comment]
@treaz If you're just trying to send a PR to help with something (which is awesome, thank you), the #4 request is old and would probably be appreciated by people.

**Pull request closed without merging**
